# Generated by Django 3.1.1 on 2020-10-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
    ]
