# Generated by Django 3.1.1 on 2020-10-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
