# Generated by Django 3.1.1 on 2020-11-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201021_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
