# Generated by Django 3.1.1 on 2020-11-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201026_1214'),
        ('core', '0004_cover'),
    ]

    operations = [
    ]
