apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app: pytime-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: pytime-api