# Generated by Django 3.1.1 on 2020-10-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favorite',
            new_name='nickName',
        ),
    ]
